[package]
name = "qsc_runtime_capabilities"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indenter = { workspace = true }
qsc_data_structures = {path = "../qsc_data_structures" }
qsc_fir = { path = "../qsc_fir" }
rustc-hash = { workspace = true }
